### ISSUE TITLE
Add tests to show users how to test snaps

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/template-snap-monorepo#3]
Right now we don't have any tests in this repository. To help users to get an understanding of how to test snaps, we should add some basic tests, at least for the snap.

I'm not sure if tests for the frontend are necessary, but we could add some anyway, to make it easier for users.

**Comment by ziad-saab** [comment]
One thing to keep in mind while testing Snaps is that neither `jsdom` nor `node` completely reflect the SES environment where Snaps are running.
