### ISSUE TITLE
Include Buffer polyfill by default

### ISSUE THREAD

**Issue by ritave** [MetaMask/template-snap-monorepo#34]
A common reported issue is that third party libraries do not work for multiple reasons.

A very common solution is to include Node's `Buffer` polyfill.

Because people think it's an error on our side, instead of their libraries, we should handle the common case.

While we shouldn't include Buffer in the core sandbox, we should include it in the templates.

## Outcome

Add Buffer polyfill to template monorepo build system

**Comment by BboyAkers** [comment]
```js
import { Buffer } from 'buffer';
globalThis.Buffer = Buffer;
```

Fixes this but I'm getting another error 😅

**Comment by BboyAkers** [comment]
> > 
> 
> what other error are you getting @BboyAkers ?

It was an internal state error butttt I think it was a problem with my environment! I should be okay now 🙂
