### ISSUE TITLE
Decide whether we want to use `allow-scripts` in template-snap-monorepo or not

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/template-snap-monorepo#4]

**Comment by rekmarks** [comment]
With Yarn 3, we don't need a custom installation script, so I'd say we can use it so long as we document it properly in the readme and reference the package's own docs.

**Comment by kritler** [comment]
(-(-_(-_-)_-)-)-)

**Comment by Montoya** [comment]
This is an old issue and not part of v1 candidates. Is this still necessary? Should we put it in the icebox @ritave?

**Comment by kenhkan** [comment]
Closing this as the team has decided that we will not use allow-scripts in this repo
