### ISSUE TITLE
wallet_requestSnaps throws error

### ISSUE THREAD

**Issue by alecps** [MetaMask/template-snap-monorepo#45]
I'm getting the error `The method "wallet_requestSnaps" does not exist / is not available.` when I hit the `connect`/ `reconnect` button on this project (without making any changes to the code). 

Steps to reproduce:

git clone git@github.com:MetaMask/template-snap-monorepo.git template-snap
cd template-snap
yarn
yarn start

and then when I hit the `connect` button I see this 

<img width="686" alt="Screenshot 2023-05-16 at 8 25 15 PM" src="https://github.com/MetaMask/template-snap-monorepo/assets/25732362/7a5b8569-e8c3-4248-b0c9-dc939a339113">

I'm on version 10.29.0-flask.0 of metamask flask

**Comment by FrederikBolding** [comment]
https://github.com/MetaMask/template-snap-monorepo/issues/46#issuecomment-1559093018
